Import Relevant Libraries

In [1]:
import numpy as np

Declaring Scalars, Vector and Matrices

Scalars

In [2]:
s = 5

In [3]:
s

5

Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data Types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

Data Shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [15]:
v.shape

(3,)

In [20]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [21]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [22]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [23]:
s_array.shape

()

Creating a Column Vector

In [24]:
m1 = np.array([[9, 8, 7],[1, 3, -5]])
m1

array([[ 9,  8,  7],
       [ 1,  3, -5]])

Tensors

In [25]:
t = np.array([m, m1])

In [26]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Checking its shape

In [27]:
t.shape

(2, 2, 3)

Addition of Matrices

In [28]:
m + m1

array([[14, 20, 13],
       [-2,  3,  9]])

In [29]:
m - m1

array([[-4,  4, -1],
       [-4, -3, 19]])

In [30]:
m * m1

array([[ 45,  96,  42],
       [ -3,   0, -70]])

In [32]:
m / m1

array([[ 0.55555556,  1.5       ,  0.85714286],
       [-3.        ,  0.        , -2.8       ]])

In [33]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [34]:
m + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [35]:
v

array([ 5, -2,  4])

In [36]:
v+1

array([ 6, -1,  5])

In [37]:
type(t)

numpy.ndarray

In [39]:
v.reshape

<function ndarray.reshape>

In [40]:
v

array([ 5, -2,  4])

In [41]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [42]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [43]:
m.reshape(3,2)

array([[ 5, 12],
       [ 6, -3],
       [ 0, 14]])

In [44]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [45]:
m.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [46]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [47]:
np.dot(x,y)

-66

In [48]:
5*x

array([ 10,  40, -20])

In [49]:
10*y

array([ 10, -70,  30])

In [50]:
np.dot(5,x)

array([ 10,  40, -20])

In [51]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [52]:
m1

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [53]:
np.dot(3,m)

array([[15, 36, 18],
       [-9,  0, 42]])

In [54]:
np.dot(m,m1)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [55]:
np.dot(m,m.T)

array([[205,  69],
       [ 69, 205]])

In [56]:
m + m.T

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [1]:
help(tuple)

Help on class tuple in module builtins:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |